language: java

jdk:
  - openjdk17

sudo: false

env:
  global:
    - CODECOV_TOKEN="38d4856e-981c-4a53-9d18-aa0859b566df"

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - malgin.zhenya@yandex.ru
    on_success: never # default: change
    on_failure: always # default: always